### ISSUE TITLE
Crash When Getting A Craving

### ISSUE THREAD

**Issue by TheLimePixel** [Darkhax-Minecraft/Cravings#1]
https://pastebin.com/6ykKwrS6

**Comment by Darkhax** [comment]
Thanks for the report. Have you configured the mod in any way? If so could I see the config changes?

**Comment by TheLimePixel** [comment]
I just added a few modded potion effects and changed the chance to 15%.

**Comment by Darkhax** [comment]
Okay, it's possible that you added a potion using an incorrect ID. If you look through the game log there will be an error message about it to let you know which specific entry. I am going to patch up this issue though, to make sure you don't crash when bad entries are added. I also plan to help make these errors a bit more obvious.

**Comment by Darkhax** [comment]
New release will fix this issue, and give you the info you need when the mod is configured incorrectly. Thanks again
