### ISSUE TITLE
Don't add foods that don't have a food value

### ISSUE THREAD

**Issue by jesmores** [Darkhax-Minecraft/Cravings#10]
I have Cravings and VanillaFoodPantry installed in Minecraft 1.12. I just got a craving for "Unbaked Salmon Potato Pie" which, as far as I know, isn't actually edible, as the tooltip (provided by Quark) doesn't show food values.

**Comment by Darkhax** [comment]
Cravings isn't really a mod that can be played with right out of the box, it's meant to be a modpack tool. The config for the mod by default is purely an example, and it is expected that modpacks go through and configure all the foods they specifically want themselves. I will consider adding this to the default setup though.

**Comment by jesmores** [comment]
Oh is the config for manually adding (or excluding) foods to the cravings list already implemented?

**Comment by TimGoll** [comment]
"Oh is the config for manually adding (or excluding) foods to the cravings list already implemented?" I'd like to know this too

**Comment by Darkhax** [comment]
The current config option is a general override that blacklists any food without a food value, and any food without a saturation value. The precise control will be coming in a future update.
