### ISSUE TITLE
Remove Cravings for Poisonous Foods

### ISSUE THREAD

**Issue by ghost** [Darkhax-Minecraft/Cravings#2]
Like the title says, I think it would be best if it was impossible to get a craving for a food that gives you the hunger debuff.

**Comment by Darkhax** [comment]
I kind of like how you can have cravings for things that are not healthy for you. However I understand where this request is coming from. The plan moving forward is to allow cravings to be set by the modpack. This would include specific rewards for specific items, different rarities of a craving, and non-potion rewards/punishments. I plan to also include a blacklist and auto-blacklist options.

**Comment by ghost** [comment]
That sounds like an even better solution! A blacklist would suit my needs perfectly!

**Comment by jesmores** [comment]
Yeah, blacklist would be most ideal, I have an uncraftable food item in my pack (BoP Ambrosia) and I got cravings for it :P

Actually it would help pack makers if the mod has an option (a command maybe, or pregenerated config) that lists out all the foods it found in the pack so we can review in an easy place.
