### ISSUE TITLE
Setting custom duration for craving satisfaction effects in config seems not to work.

### ISSUE THREAD

**Issue by TeetoKaziim** [Darkhax-Minecraft/Cravings#4]
On: 
Cravings 1.0.3
Minecraft 1.12.2
Forge 14.23.1.2556

My config file looks like this:
https://pastebin.com/raw/63Xjnshd

With most of the effects, besides regeneration, set to 7200 ticks. The effects trigger, and work, but always seem to last 10 seconds. I've also tried 3600 ticks. (Maybe there's some maximum amount I'm not aware of?)

Lovin the mod though, it's a neat take on expanding the various food cooking mods utility without resorting to heavy handed nerfing.

**Comment by Darkhax** [comment]
Thanks for the report. I will look into it and get back to you once I have worked out the issue.

**Comment by Darkhax** [comment]
After looking into your issue a bit further, it seems the input is incorrect. 10 seconds is what it will default to if it can not find a valid number string. Looking at your config there seems to be some spacing issues with some lines, try fixing those? If you play around with the default settings, none of the ones with a set time will have 10 seconds.

**Comment by TeetoKaziim** [comment]
Oh no user error. Sorry for the wild goose chase. I'll mess with it. Thanks for the heads up :D.
