### ISSUE TITLE
Mod foods not being added to pool of possible cravings?

### ISSUE THREAD

**Issue by jesmores** [Darkhax-Minecraft/Cravings#5]
I'm using Cravings with Vanilla Food Pantry and I've not seen a craving for any of VFP's foods yet. Is there a way to print to the console all foods that the mod has recognized, so I can be sure that is the case and not just my luck?

Cravings-1.12.2-1.0.3
VanillaFoodPantry-mc1.12.1-4.0.0

I also have the Nutrition mod installed, in case that is relevant.
Nutrition-1.12.2-2.5.0

Minecraft 1.12.2
Forge-14.23.1.2555

**Comment by Darkhax** [comment]
Thanks for reporting the issue, and sorry it took so long to fix. The next update has a `/craving foods` command which will print all of the detected foods. I also fixed a bug that would prevent some foods from being detected.

**Comment by Darkhax** [comment]
https://minecraft.curseforge.com/projects/cravings/files/2509860
