### ISSUE TITLE
[Bug] Cravings still present in Creative mode

### ISSUE THREAD

**Issue by ghost** [Darkhax-Minecraft/Cravings#7]
Like the titles says, cravings are still active in creative mode (evidenced by the occasional chat message stating failure), even though they have no purpose there.

**Comment by Darkhax** [comment]
Thanks for the report. In the next version players in creative mode will not have the craving timer tick down.

**Comment by Darkhax** [comment]
This should be fixed in the next release on CurseForge.

**Comment by Darkhax** [comment]
https://minecraft.curseforge.com/projects/cravings/files/2509860
