### ISSUE TITLE
Setting an Amplifier in the Config makes it ignore entered duration value and use 200 ticks instead.

### ISSUE THREAD

**Issue by TeetoKaziim** [Darkhax-Minecraft/Cravings#8]
Forge Mod Loader version 14.23.1.2566 for Minecraft 1.12.2
Bookshelf-1.12.2-2.3.511
Cravings-1.12.2-1.0.5
Hwyla-1.8.23-B38_1.12
InventoryTweaks-1.63
jei_1.12.2-4.8.5.136

Config File I'm Using: https://pastebin.com/raw/D8r1ePau

I wasn't sure if I should do this as a new issue, or reopen the one you closed (I'm a n00b and don't know the etiquette here), but I think I tracked down and can reproduce. The only changes I made in my config from the defaults the mod ships with in my testing instance were the following lines:
```
S:cravingChance=1
I:ticksTillCravingAttempt=100
```
To make testing easier. 

According to that config, this line: 
```
        minecraft:regeneration, 100, 2
```
Should give you "Regeneration III" for 5 seconds (100 ticks). But instead, it gives you "Regeneration III" for 10 seconds (200 ticks).
The other potion effects that lack an amplifier value go for the full 5 minutes (6000 ticks) like they are supposed to.

Sorry to be a gnat buzzing around your head, but I figured after pinning down the cause more concisely, I figured you'd want to know. Thanks for your patience, and for the mod.

**Comment by Darkhax** [comment]
Ah, I see the issue now! Thanks for tracking this down a bit further for me!

**Comment by Darkhax** [comment]
[This](https://minecraft.curseforge.com/projects/cravings/files/2510210) release should help you fix your issue. Let me know if it worked.

**Comment by TeetoKaziim** [comment]
Oh gosh sorry about the delay, yes, absolutely. Satisfying my craving for golden carrot gave me 5 minutes of Luck III, just like I always wanted :D.

Thanks so much, and best of luck!

**Comment by Darkhax** [comment]
Glad it works :)
