### ISSUE TITLE
Ticking Entity error crash (SMP Only)

### ISSUE THREAD

**Issue by Axebeard2025** [Darkhax-Minecraft/Cravings#9]
I kept getting "Error: java.lang.NullPointerException: Ticking entity" crashes when connecting to a multiplayer server, but it did not happen when creating a survival single-player game

(I've included crash logs for Forge 1.12.2-14.23.1.2555 without Mercurius, Bookshelf 1.12.2-2.3.513, Cravings 1.12.2-1.0.5.  If you need to see the logs for that test pack from the other test packs, just let me know and I'll send them along.)

This behavior was seen with the following combinations:

	- Forge 1.12.2-14.23.1.2555 without Mercurius, Bookshelf 1.12.2-2.3.514, Cravings 1.12.2-1.0.5
	- Forge 1.12.2-14.23.1.2555 without Mercurius, Bookshelf 1.12.2-2.3.514, Cravings 1.12.2-1.0.6

	- Forge 1.12.2-14.23.1.2555 without Mercurius, Bookshelf 1.12.2-2.3.513, Cravings 1.12.2-1.0.5
	- Forge 1.12.2-14.23.1.2555 without Mercurius, Bookshelf 1.12.2-2.3.513, Cravings 1.12.2-1.0.6

	- Forge 1.12.2-14.23.1.2555 without Mercurius, Bookshelf 1.12.2-2.3.512, Cravings 1.12.2-1.0.5
	- Forge 1.12.2-14.23.1.2555 without Mercurius, Bookshelf 1.12.2-2.3.512, Cravings 1.12.2-1.0.6		

	- Forge 1.12.2-14.23.1.2581 without Mercurius, Bookshelf 1.12.2-2.3.514, Cravings 1.12.2-1.0.5
	- Forge 1.12.2-14.23.1.2581 without Mercurius, Bookshelf 1.12.2-2.3.514, Cravings 1.12.2-1.0.6
	
	- Forge 1.12.2-14.23.1.2581 without Mercurius, Bookshelf 1.12.2-2.3.513, Cravings 1.12.2-1.0.5
	- Forge 1.12.2-14.23.1.2555 without Mercurius, Bookshelf 1.12.2-2.3.513, Cravings 1.12.2-1.0.6
	
	- Forge 1.12.2-14.23.1.2581 without Mercurius, Bookshelf 1.12.2-2.3.512, Cravings 1.12.2-1.0.5
	- Forge 1.12.2-14.23.1.2581 without Mercurius, Bookshelf 1.12.2-2.3.512, Cravings 1.12.2-1.0.6
	
This behavior was absent from the following combinations:
	
	- Forge 1.12.2-14.23.1.2555 without Mercurius, Bookshelf 1.12.2-2.3.511, Cravings 1.12.2-1.0.5			
	- Forge 1.12.2-14.23.1.2555 without Mercurius, Bookshelf 1.12.2-2.3.511, Cravings 1.12.2-1.0.6
	- Forge 1.12.2-14.23.1.2581 without Mercurius, Bookshelf 1.12.2-2.3.511, Cravings 1.12.2-1.0.5	
	- Forge 1.12.2-14.23.1.2581 without Mercurius, Bookshelf 1.12.2-2.3.511, Cravings 1.12.2-1.0.6	

Client Logs
[crash-2017-12-23_19.33.38-client.txt](https://github.com/Darkhax-Minecraft/Cravings/files/1584551/crash-2017-12-23_19.33.38-client.txt)
[latest.log](https://github.com/Darkhax-Minecraft/Cravings/files/1584552/latest.log)
[fml-junk-earlystartup.log](https://github.com/Darkhax-Minecraft/Cravings/files/1584553/fml-junk-earlystartup.log)
[fml-client-latest.log](https://github.com/Darkhax-Minecraft/Cravings/files/1584555/fml-client-latest.log)

Server Logs
[fml-server-latest.log](https://github.com/Darkhax-Minecraft/Cravings/files/1584556/fml-server-latest.log)
[latest.log](https://github.com/Darkhax-Minecraft/Cravings/files/1584557/latest.log)
[fml-junk-earlystartup.log](https://github.com/Darkhax-Minecraft/Cravings/files/1584558/fml-junk-earlystartup.log)

**Comment by Darkhax** [comment]
Hi, thanks for the report. This is an issue with the latest build of bookshelf. I should have a fix out later tonight.

**Comment by Darkhax** [comment]
Does this issue still exist with [518](https://minecraft.curseforge.com/projects/bookshelf/files/2514598)?
